sudo: false
dist: xenial
language: php

matrix:
  include:
    - php: 5.3
      dist: precise
      env: DISABLE_PHP_CS_FIXER=true
    - php: 5.4
      dist: trusty
      env: DISABLE_PHP_CS_FIXER=true
    - php: 5.5
      dist: trusty
      env: DISABLE_PHP_CS_FIXER=true
    - php: 5.6
      dist: trusty
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

branches:
  only:
    - devel
    - master

before_script:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0
  - composer install --no-interaction
  - if [ "$DISABLE_PHP_CS_FIXER" != true ]; then composer create-project --no-dev --no-interaction friendsofphp/php-cs-fixer /tmp/php-cs-fixer ^2.15; fi

script:
  - if [ "$DISABLE_PHP_CS_FIXER" != true ]; then /tmp/php-cs-fixer/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no; fi
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit -v -c tests/phpunit.xml --coverage-text --strict-coverage --stop-on-risky

notifications:
  email:
    recipients:
      - serbanghita@gmail.com
    on_success: never
    on_failure: always
  slack:
    rooms:
      - mobiledetect:in9qB4EvOrdR5v1E8V0nNqsJ#general
  irc:
    channels:
      - "asimov.freenode.net#mobiledetect"
    template:
      - "%{repository} (%{commit}): %{message}. Build details: %{build_url}"
      - "%{author} said %{commit_subject}. See %{compare_url}"
